-- MySQL Script generated by MySQL Workbench
-- Sat Apr 29 16:41:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema livraria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema livraria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `livraria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema livraria1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema livraria1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `livraria1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `livraria` ;

-- -----------------------------------------------------
-- Table `livraria`.`livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livraria`.`livro` ;

CREATE TABLE IF NOT EXISTS `livraria`.`livro` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ano_publicacao` INT NOT NULL,
  `autor` VARCHAR(255) NULL DEFAULT NULL,
  `destaque` BIT(1) NULL DEFAULT NULL,
  `editora` VARCHAR(255) NULL DEFAULT NULL,
  `genero` VARCHAR(255) NULL DEFAULT NULL,
  `imagem` VARCHAR(255) NULL DEFAULT NULL,
  `oferta` BIT(1) NULL DEFAULT NULL,
  `qtde_pagina` INT NOT NULL,
  `sinopse` LONGTEXT NULL DEFAULT NULL,
  `titulo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livraria`.`detalhe_livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livraria`.`detalhe_livro` ;

CREATE TABLE IF NOT EXISTS `livraria`.`detalhe_livro` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `preco` DECIMAL(38,2) NULL DEFAULT NULL,
  `qtde_estoque` INT NOT NULL,
  `tipo_livro` VARCHAR(255) NULL DEFAULT NULL,
  `id_livro` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK27v8al1wu7sxm39k7n3ecos1k` (`id_livro` ASC) VISIBLE,
  CONSTRAINT `FK27v8al1wu7sxm39k7n3ecos1k`
    FOREIGN KEY (`id_livro`)
    REFERENCES `livraria`.`livro` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livraria`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livraria`.`usuario` ;

CREATE TABLE IF NOT EXISTS `livraria`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(255) NULL DEFAULT NULL,
  `data_cadastro` DATE NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livraria`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livraria`.`endereco` ;

CREATE TABLE IF NOT EXISTS `livraria`.`endereco` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(255) NULL DEFAULT NULL,
  `cep` VARCHAR(255) NULL DEFAULT NULL,
  `cidade` VARCHAR(255) NULL DEFAULT NULL,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `logradouro` VARCHAR(255) NULL DEFAULT NULL,
  `numero` VARCHAR(255) NULL DEFAULT NULL,
  `uf` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK233cf5mftynvlqs8ydwjlgf0i` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK233cf5mftynvlqs8ydwjlgf0i`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `livraria`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livraria`.`favorito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livraria`.`favorito` ;

CREATE TABLE IF NOT EXISTS `livraria`.`favorito` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `id_livro` BIGINT NULL DEFAULT NULL,
  `id_usuario` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK8al49s4yme3jyhs66xj8fmy7o` (`id_livro` ASC) VISIBLE,
  INDEX `FK5vmlgfa4nyi848sknxb237yjt` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK5vmlgfa4nyi848sknxb237yjt`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `livraria`.`usuario` (`id`),
  CONSTRAINT `FK8al49s4yme3jyhs66xj8fmy7o`
    FOREIGN KEY (`id_livro`)
    REFERENCES `livraria`.`livro` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livraria`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livraria`.`pedido` ;

CREATE TABLE IF NOT EXISTS `livraria`.`pedido` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_pedido` DATE NULL DEFAULT NULL,
  `usuario` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKcue42wbaxuo9hu7cy2ixrokx5` (`usuario` ASC) VISIBLE,
  CONSTRAINT `FKcue42wbaxuo9hu7cy2ixrokx5`
    FOREIGN KEY (`usuario`)
    REFERENCES `livraria`.`usuario` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livraria`.`item_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livraria`.`item_pedido` ;

CREATE TABLE IF NOT EXISTS `livraria`.`item_pedido` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `qtde_itens` INT NOT NULL,
  `valor_total` DECIMAL(38,2) NULL DEFAULT NULL,
  `valor_unid` DECIMAL(38,2) NULL DEFAULT NULL,
  `id_detalhe_livro` BIGINT NULL DEFAULT NULL,
  `id_pedido` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK5vsu1oh0knfwognqlpb62tk6v` (`id_detalhe_livro` ASC) VISIBLE,
  INDEX `FKnjghutiejefh2auj9bnpf9sp7` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `FK5vsu1oh0knfwognqlpb62tk6v`
    FOREIGN KEY (`id_detalhe_livro`)
    REFERENCES `livraria`.`detalhe_livro` (`id`),
  CONSTRAINT `FKnjghutiejefh2auj9bnpf9sp7`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `livraria`.`pedido` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `livraria1` ;

-- -----------------------------------------------------
-- Table `livraria1`.`livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livraria1`.`livro` ;

CREATE TABLE IF NOT EXISTS `livraria1`.`livro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `imagem` BLOB NULL DEFAULT NULL,
  `autor` VARCHAR(100) NULL DEFAULT NULL,
  `sinopse` BLOB NULL DEFAULT NULL,
  `genero` VARCHAR(30) NULL DEFAULT NULL,
  `editora` VARCHAR(50) NULL DEFAULT NULL,
  `ano_Publicacao` INT NULL DEFAULT NULL,
  `qtde_pagina` INT NULL DEFAULT NULL,
  `oferta` TINYINT(1) NULL DEFAULT NULL,
  `destaque` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livraria1`.`detalhe_livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livraria1`.`detalhe_livro` ;

CREATE TABLE IF NOT EXISTS `livraria1`.`detalhe_livro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_livro` ENUM('Ebook', 'Fisico') NULL DEFAULT NULL,
  `preco` INT NOT NULL,
  `id_livro` INT NOT NULL,
  `qtde_estoque` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_livro` (`id_livro` ASC) VISIBLE,
  CONSTRAINT `detalhe_livro_ibfk_1`
    FOREIGN KEY (`id_livro`)
    REFERENCES `livraria1`.`livro` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livraria1`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livraria1`.`usuario` ;

CREATE TABLE IF NOT EXISTS `livraria1`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `data_cadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livraria1`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livraria1`.`endereco` ;

CREATE TABLE IF NOT EXISTS `livraria1`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uf` CHAR(2) NOT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(30) NOT NULL,
  `numero` CHAR(10) NOT NULL,
  `complemento` VARCHAR(10) NULL DEFAULT NULL,
  `cep` CHAR(8) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `endereco_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `livraria1`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livraria1`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livraria1`.`pedido` ;

CREATE TABLE IF NOT EXISTS `livraria1`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_pedido` DATE NULL DEFAULT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `pedido_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `livraria1`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `livraria1`.`item_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `livraria1`.`item_pedido` ;

CREATE TABLE IF NOT EXISTS `livraria1`.`item_pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `qtde` VARCHAR(2) NOT NULL,
  `id_pedido` INT NOT NULL,
  `id_detalhe_livro` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_pedido` (`id_pedido` ASC) VISIBLE,
  INDEX `id_detalhe_livro` (`id_detalhe_livro` ASC) VISIBLE,
  CONSTRAINT `item_pedido_ibfk_1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `livraria1`.`pedido` (`id`),
  CONSTRAINT `item_pedido_ibfk_2`
    FOREIGN KEY (`id_detalhe_livro`)
    REFERENCES `livraria1`.`detalhe_livro` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
